version: '3.8'

services:
  suc-api:
    build:
      context: ./su-api
    image: suc/suc-api:1.0.0
    container_name: suc_api
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://suc-db:5432/suc_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    depends_on:
      - db

  suc-website:
    build:
      context: ./su-website
    image: suc/suc-website:1.0.0
    container_name: suc-website
    ports:
      - '5000:80'
    depends_on:
      - suc-api

  db:
    image: postgres:latest
    container_name: suc-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: suc_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
